# Generated by Django 2.2.1 on 2019-08-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='quantity',
        ),
    ]
