# Generated by Django 2.2.1 on 2019-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
