# Generated by Django 2.2.1 on 2019-09-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190818_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='basket_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
