# Generated by Django 2.2.1 on 2019-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_basket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='meal',
            field=models.ManyToManyField(to='users.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
